### ISSUE TITLE
Нет возможности настроить приложение

### ISSUE THREAD

**Issue by dronchik** [q3mi4/testing#1]
Установленное приложение требует чтобы mongod слушал localhost:27017. Было бы хорошо, иметь возможность изменить настройки соединения к БД и вынести их в отдельных файл, который можно менять. 

Но даже когда я руками поменял параметры хоста и порта, то приложение не заработало и не вывело мне ничего.

**Comment by q3mi4** [comment]
Добавил конфиг-файл для БД config.json

**приложение не заработало**
Какие либо ошибки выводятся?
mcli должен работать и вывести приглашение даже без подключения в БД.

возможно не отрабатывает #!/usr/bin/env php вначале файла mcli, попробуйте запустить как 
`$ php mcli`

Проверял с помощью travis, лог можно посмотреть тут: https://api.travis-ci.org/jobs/174467225/log.txt?deansi=true

**Comment by dronchik** [comment]
Ага, я понял в чем проблема, конфиги то теперь вынесены, а имя самой БД `mev` захардкожено вот тут:
```php
return $manager->executeQuery("mev.{$collection}", $query);
```
И тесты так же выполняются только на специфичных данных (фикстурах), которые он сам же и должен заполнять в БД, по хорошему.

В общем мне удалось завести. Спасибо!
